package com.udt.db;
// Generated Aug 21, 2012 6:50:54 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DeviceBind generated by hbm2java
 */
public class DeviceBind  implements java.io.Serializable {


     private Long id;
     private long accountId;
     private String token;
     private String version;
     private Date time;

    public DeviceBind() {
    }

    public DeviceBind(long accountId, String token, String type, Date time) {
       this.accountId = accountId;
       this.token = token;
       this.version = type;
       this.time = time;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(long accountId) {
        this.accountId = accountId;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String type) {
        this.version = type;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


