package com.udt.db;
// Generated Oct 18, 2012 5:16:15 PM by Hibernate Tools 3.2.1.GA



/**
 * DingFavorite generated by hbm2java
 */
public class DingFavorite  implements java.io.Serializable {


     private Long id;
     private String class_;
     private long groupId;
     private long accountId;

    public DingFavorite() {
    }

    public DingFavorite(String class_, long groupId, long accountId) {
       this.class_ = class_;
       this.groupId = groupId;
       this.accountId = accountId;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
    public long getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(long groupId) {
        this.groupId = groupId;
    }
    public long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(long accountId) {
        this.accountId = accountId;
    }




}


