package com.udt.db;
// Generated Oct 18, 2012 5:16:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DingPush generated by hbm2java
 */
public class DingPush  implements java.io.Serializable {


     private Long id;
     private long productId;
     private String storeName;
     private String class_;
     private String name;
     private Date effectiveTime;
     private Date expiredTime;
     private long accountId;
     private String email;
     private long groupId;
     private float priceThreshold;

    public DingPush() {
    }

	
    public DingPush(long productId, String storeName, String class_, String name, long accountId, String email, long groupId, float priceThreshold) {
        this.productId = productId;
        this.storeName = storeName;
        this.class_ = class_;
        this.name = name;
        this.accountId = accountId;
        this.email = email;
        this.groupId = groupId;
        this.priceThreshold = priceThreshold;
    }
    public DingPush(long productId, String storeName, String class_, String name, Date effectiveTime, Date expiredTime, long accountId, String email, long groupId, float priceThreshold) {
       this.productId = productId;
       this.storeName = storeName;
       this.class_ = class_;
       this.name = name;
       this.effectiveTime = effectiveTime;
       this.expiredTime = expiredTime;
       this.accountId = accountId;
       this.email = email;
       this.groupId = groupId;
       this.priceThreshold = priceThreshold;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getProductId() {
        return this.productId;
    }
    
    public void setProductId(long productId) {
        this.productId = productId;
    }
    public String getStoreName() {
        return this.storeName;
    }
    
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getEffectiveTime() {
        return this.effectiveTime;
    }
    
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }
    public Date getExpiredTime() {
        return this.expiredTime;
    }
    
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }
    public long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(long accountId) {
        this.accountId = accountId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public long getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(long groupId) {
        this.groupId = groupId;
    }
    public float getPriceThreshold() {
        return this.priceThreshold;
    }
    
    public void setPriceThreshold(float priceThreshold) {
        this.priceThreshold = priceThreshold;
    }




}


