package com.udt.db;
// Generated Oct 18, 2012 5:16:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DingAccount generated by hbm2java
 */
public class DingAccount  implements java.io.Serializable {


     private Long id;
     private String username;
     private String email;
     private String password;
     private String passwordSalt;
     private String role;
     private Date registerTime;

    public DingAccount() {
    }

    public DingAccount(String username, String email, String password, String passwordSalt, String role, Date registerTime) {
       this.username = username;
       this.email = email;
       this.password = password;
       this.passwordSalt = passwordSalt;
       this.role = role;
       this.registerTime = registerTime;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPasswordSalt() {
        return this.passwordSalt;
    }
    
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Date getRegisterTime() {
        return this.registerTime;
    }
    
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }




}


