package com.udt.db;
// Generated Oct 18, 2012 5:16:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DingAccountRegister generated by hbm2java
 */
public class DingAccountRegister  implements java.io.Serializable {


     private String code;
     private String username;
     private String email;
     private String password;
     private String passwordSalt;
     private Date registerTime;

    public DingAccountRegister() {
    }

    public DingAccountRegister(String code, String username, String email, String password, String passwordSalt, Date registerTime) {
       this.code = code;
       this.username = username;
       this.email = email;
       this.password = password;
       this.passwordSalt = passwordSalt;
       this.registerTime = registerTime;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPasswordSalt() {
        return this.passwordSalt;
    }
    
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt;
    }
    public Date getRegisterTime() {
        return this.registerTime;
    }
    
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }




}


