package com.udt.db;
// Generated Oct 18, 2012 5:16:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DingDeviceBind generated by hbm2java
 */
public class DingDeviceBind  implements java.io.Serializable {


     private long id;
     private String version;
     private long accountId;
     private String uuid;
     private String token;
     private Date time;

    public DingDeviceBind() {
    }

    public DingDeviceBind(long id, long accountId, String uuid, String token, Date time) {
       this.id = id;
       this.accountId = accountId;
       this.uuid = uuid;
       this.token = token;
       this.time = time;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(long accountId) {
        this.accountId = accountId;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


