package com.udt.db;
// Generated Oct 18, 2012 5:16:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DingFeedback generated by hbm2java
 */
public class DingFeedback  implements java.io.Serializable {


     private Long id;
     private String contact;
     private String content;
     private Date time;
     private String comment;

    public DingFeedback() {
    }

    public DingFeedback(String contact, String content, Date time, String comment) {
       this.contact = contact;
       this.content = content;
       this.time = time;
       this.comment = comment;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


