package com.udt.db;
// Generated Aug 21, 2012 6:50:54 PM by Hibernate Tools 3.2.1.GA



/**
 * Favorite generated by hbm2java
 */
public class Favorite  implements java.io.Serializable {


     private Long id;
     private String type;
     private int productId;
     private long accountId;

    public Favorite() {
    }

    public Favorite(String type, int productId, long accountId) {
       this.type = type;
       this.productId = productId;
       this.accountId = accountId;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(long accountId) {
        this.accountId = accountId;
    }




}


