package com.udt.db;
// Generated Aug 21, 2012 6:50:54 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Observer generated by hbm2java
 */
public class Observer  implements java.io.Serializable {


     private Long observerId;
     private String storePid;
     private String storeName;
     private String type;
     private int productId;
     private String name;
     private Date effectiveTime;
     private Date expiredTime;
     private double priceThreshold;
     private long accountId;
     private String email;

    public Observer() {
    }

	
    public Observer(String type, int productId, String name, Date effectiveTime, Date expiredTime, double priceThreshold, long accountId, String email) {
        this.type = type;
        this.productId = productId;
        this.name = name;
        this.effectiveTime = effectiveTime;
        this.expiredTime = expiredTime;
        this.priceThreshold = priceThreshold;
        this.accountId = accountId;
        this.email = email;
    }
    public Observer(String storePid, String storeName, String type, int productId, String name, Date effectiveTime, Date expiredTime, double priceThreshold, long accountId, String email) {
       this.storePid = storePid;
       this.storeName = storeName;
       this.type = type;
       this.productId = productId;
       this.name = name;
       this.effectiveTime = effectiveTime;
       this.expiredTime = expiredTime;
       this.priceThreshold = priceThreshold;
       this.accountId = accountId;
       this.email = email;
    }
   
    public Long getObserverId() {
        return this.observerId;
    }
    
    public void setObserverId(Long observerId) {
        this.observerId = observerId;
    }
    public String getStorePid() {
        return this.storePid;
    }
    
    public void setStorePid(String storePid) {
        this.storePid = storePid;
    }
    public String getStoreName() {
        return this.storeName;
    }
    
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getEffectiveTime() {
        return this.effectiveTime;
    }
    
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }
    public Date getExpiredTime() {
        return this.expiredTime;
    }
    
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }
    public double getPriceThreshold() {
        return this.priceThreshold;
    }
    
    public void setPriceThreshold(double priceThreshold) {
        this.priceThreshold = priceThreshold;
    }
    public long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(long accountId) {
        this.accountId = accountId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


